version: "3"
services:
    web:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
            - "1234:80"
        depends_on:
            - db
        networks:
            - my-network
    db:
        image: "mcr.microsoft.com/mssql/server"
        ports:
            - "2000:1433"
        environment:
            SA_PASSWORD: "Gabriel@12345"
            ACCEPT_EULA: "Y"
        networks:
            - my-network
    # migration:
    #     build:
    #       context: .
    #       dockerfile: DockerfileMigration
    #     ports:
    #         - "8000:80"
    #     depends_on:
    #         - db
    #     networks:
    #         - my-network
networks:
    my-network:
        driver: bridge