apiVersion : apps/v1
kind: Deployment
metadata:
  name: orderimport-deployment 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orderimport
  template:
    metadata:
      labels:
        app: orderimport
    spec:
      containers:
        - name: orderimport
          image: orderimport
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: gnalmeida1412a2b1-auth

---

apiVersion: v1
kind: Service
metadata:
    name: orderimport
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: orderimport